#!/usr/bin/env bash
#
# Copyright HamoniKR Project. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.


if [[ -d "/usr/share/backgrounds/linuxmint-wilma/" ]]; then
    rm -frv /usr/share/backgrounds/linuxmint-wilma || true
    rm -frv /usr/share/cinnamon-background-properties/linuxmint-wilma.xml || true
    rm -frv /usr/share/gnome-background-properties/linuxmint-wilma.xml || true
    rm -frv /usr/share/mate-background-properties/linuxmint-wilma.xml || true
    rm -frv /usr/share/doc/mint-backgrounds-wilma || true
    rm -frv /usr/share/xfce4/backdrops/wilma* || true
    rm -frv /usr/share/wallpapers/*Wilma* || true
fi
